config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'miscellaneous#blank_page'

  # AJAX
  get 'ajax/email_compose', to: 'ajax#email_compose', as: :ajax_email_compose
  get 'ajax/email_list', to: 'ajax#email_list', as: :ajax_email_list
  get 'ajax/email_opened', to: 'ajax#email_opened', as: :ajax_email_opened
  get 'ajax/email_reply', to: 'ajax#email_reply', as: :ajax_email_reply
  get 'ajax/demo_widget', to: 'ajax#demo_widget', as: :ajax_demo_widget
  get 'ajax/data_list.json', to: 'ajax#data_list', as: :ajax_data_list
  get 'ajax/notify_mail', to: 'ajax#notify_mail', as: :ajax_notify_mail
  get 'ajax/notify_notifications',
      to: 'ajax#notify_notifications',
      as: :ajax_notify_notifications
  get 'ajax/notify_tasks', to: 'ajax#notify_tasks', as: :ajax_notify_tasks

  # Misc methods
  get '/home/set_locale', to: 'home#set_locale', as: :home_set_locale

  # CK editor
  mount Ckeditor::Engine => '/ckeditor'
  
  # WX base
  get 'wx/messages', to: 'wx_base#verify_token'
  post 'wx/messages', to: 'wx_base#messages'
  
  # WX page
  get 'messages', to: 'wx_page#messages'
  get 'followers', to: 'wx_page#followers'
  
  # SN Generator
  get 'sn', to: 'series_number#list'
  get 'sn/new', to: 'series_number#new'
  post 'sn/new', to: 'series_number#new'
  get 'sn/dl/:key', to: 'series_number#download', as: :sn_dl

end

app/controllers/ajax_controller.rb
# AJAX helpers
class AjaxController < ApplicationController
  layout false

  def email_list
  end

  def email_compose
  end

  def email_opened
  end

  def email_reply
  end

  def demo_widget
  end

  def data_list
  end

  def notify_mail
  end

  def notify_notifications
  end

  def notify_tasks
  end
end

app/views/ajax/demo_widget.html.haml
%p.alert.alert-info
  This widget is fetching data from an external source with the use of code
  = succeed "." do
    %code
      data-widget-load="
      %i.text-primary> [data source]
      "
  %code data-widget-refresh="15"
  , which will refresh the widget and fetch the data every 15 seconds.
/ dummy file
.row
  .col-sm-7
    %code
      data-widget-load="
      %i.text-primary> ajax/demo_widget
      "
  .col-sm-5.text-right
    .jarviswidget-timestamp.no-margin
#flotcontainer{:style => "height:200px; width:100%;"}
:javascript
  /*
  * RUN PAGE GRAPHS
  */
	
  // Load FLOAT dependencies (related to page)
  loadScript("#{javascript_path 'plugin/flot/jquery.flot.cust.js'}", loadFlotResize);
	
  function loadFlotResize() {
  	loadScript("#{javascript_path 'plugin/flot/jquery.flot.resize.js'}", loadFlotToolTip);
  }
	
  function loadFlotToolTip() {
  	loadScript("#{javascript_path 'plugin/flot/jquery.flot.tooltip.min.js'}", generateRandomFlot);
  }

  function generateRandomFlot(){

      function GenerateSeries(added){
          var data = [];
          var start = 100 + added;
          var end = 500 + added;
   
          for(i=1;i<=20;i++){        
              var d = Math.floor(Math.random() * (end - start + 1) + start);        
              data.push([i, d]);
              start++;
              end++;
          }
   
          return data;
      }
   
      var data1 = GenerateSeries(0);
      var data2 = GenerateSeries(10);    
   
      var markings = [
          { xaxis: { from: 1, to: 2 }, color: "#E8E8E8" },
          { xaxis: { from: 4, to: 5 }, color: "#E8E8E8" },
          { xaxis: { from: 7, to: 8 }, color: "#E8E8E8" },
          { xaxis: { from: 10, to: 11 }, color: "#E8E8E8" },
          { xaxis: { from: 13, to: 14 }, color: "#E8E8E8" },
          { xaxis: { from: 16, to: 17 }, color: "#E8E8E8" },
          { xaxis: { from: 19, to: 20 }, color: "#E8E8E8" }
   
      ];
   
      var options = {            
               series: {
                  lines: { show: true, lineWidth: 3 },
                  shadowSize: 0
              },
              grid: {
                  markings: markings,
                  backgroundColor: { colors: ["#D1D1D1", "#7A7A7A"] }
              }      
      };
   
      $.plot($("#flotcontainer"),
          [
              {data:data1},
              {data:data2}
          ], options
      );

  }

app/views/ajax/email_compose.html.haml
%h2.email-open-header
  Compose New Email
  %span.label.txt-color-white DRAFT
  %a.txt-color-darken.pull-right{"data-original-title" => "Print", "data-placement" => "left", :href => "javascript:void(0);", :rel => "tooltip"}
    %i.fa.fa-print
%form#email-compose-form.form-horizontal{:action => "dummy.php", :enctype => "multipart/form-data", :method => "POST"}
  .inbox-info-bar.no-padding
    .row
      .form-group
        %label.control-label.col-md-1
          %strong To
        .col-md-11
          %select.select2{"data-select-search" => "true", :multiple => "multiple", :style => "width:100%"}
            %option{:value => "sunny.orlaf@smartadmin.com"} sadi.orlaf@smartadmin.com
            %option{:value => "rachael.hawi@smartadmin.com"} rachael.hawi@smartadmin.com
            %option{:value => "michael.safiel@smartadmin.com"} michael.safiel@smartadmin.com
            %option{:value => "alex.jones@infowars.com"} alex.jones@infowars.com
            %option{:value => "oruf.matalla@gmail.com"} oruf.matalla@gmail.com
            %option{:value => "hr@smartadmin.com"} hr@smartadmin.com
            %option{:selected => "selected", :value => "IT@smartadmin.com"} IT@smartadmin.com
          %em
            %a.show-next{"data-original-title" => "Carbon Copy", "data-placement" => "bottom", :href => "javascript:void(0);", :rel => "tooltip"} CC
  .inbox-info-bar.no-padding.hidden
    .row
      .form-group
        %label.control-label.col-md-1
          %strong CC
        .col-md-11
          %select.select2{"data-select-search" => "true", :multiple => "multiple", :style => "width:100%"}
            %option{:selected => "selected", :value => "sunny.orlaf@smartadmin.com"} sunny.orlaf@smartadmin.com
            %option{:selected => "selected", :value => "rachael.hawi@smartadmin.com"} rachael.hawi@smartadmin.com
            %option{:value => "michael.safiel@smartadmin.com"} michael.safiel@smartadmin.com
            %option{:value => "alex.jones@infowars.com"} alex.jones@infowars.com
            %option{:value => "oruf.matalla@gmail.com"} oruf.matalla@gmail.com
            %option{:value => "hr@smartadmin.com"} hr@smartadmin.com
            %option{:value => "IT@smartadmin.com"} IT@smartadmin.com
          %em
            %a.show-next{"data-original-title" => "Blind Carbon Copy", "data-placement" => "bottom", :href => "javascript:void(0);", :rel => "tooltip"} BCC
  .inbox-info-bar.no-padding.hidden
    .row
      .form-group
        %label.control-label.col-md-1
          %strong BCC
        .col-md-11
          %select.select2{"data-select-search" => "true", :multiple => "multiple", :style => "width:100%"}
            %option{:value => "sunny.orlaf@smartadmin.com"} sunny.orlaf@smartadmin.com
            %option{:value => "rachael.hawi@smartadmin.com"} rachael.hawi@smartadmin.com
            %option{:value => "michael.safiel@smartadmin.com"} michael.safiel@smartadmin.com
            %option{:value => "alex.jones@infowars.com"} alex.jones@infowars.com
            %option{:value => "oruf.matalla@gmail.com"} oruf.matalla@gmail.com
            %option{:value => "hr@smartadmin.com"} hr@smartadmin.com
            %option{:value => "IT@smartadmin.com"} IT@smartadmin.com
  .inbox-info-bar.no-padding
    .row
      .form-group
        %label.control-label.col-md-1
          %strong Subject
        .col-md-11
          %input.form-control{:placeholder => "Email Subject", :type => "text"}/
          %em
            %a.show-next{"data-original-title" => "Attachments", "data-placement" => "bottom", :href => "javascript:void(0);", :rel => "tooltip"}
              %i.fa.fa-paperclip.fa-lg
  .inbox-info-bar.no-padding.hidden
    .row
      .form-group
        %label.control-label.col-md-1
          %strong Attachments
        .col-md-11
          %input.form-control.fileinput{:multiple => "multiple", :type => "file"}/
  .inbox-message.no-padding
    #emailbody
      %br/
      %br/
      %br/
      %br/
      = succeed "Thanks," do
        %br/
      %br/
      %strong John Doe
      %br/
      %br/
      %small
        CEO - SmartAdmin
        %br/
        231 Ajax Rd, Detroit MI - 48212, USA
        %br/
        %i.fa.fa-phone (313) 647 4761
      %br/
      = image_tag 'logo-blacknwhite.png', height: '20', width: 'auto', style: 'margin-top:7px; padding-right:9px; border-right:1px dotted #9B9B9B;'
  .inbox-compose-footer
    %button.btn.btn-danger{:type => "button"}
      Disregard
    %button.btn.btn-info{:type => "button"}
      Draft
    %button#send.btn.btn-primary.pull-right{"data-loading-text" => "<i class='fa fa-refresh fa-spin'></i>   Sending...", :type => "button"}
      Send
      %i.fa.fa-arrow-circle-right.fa-lg
.email-infobox
  .well.well-sm.well-light
    %h5 Related Invoice
    %ul.list-unstyled
      %li
        %i.fa.fa-file.fa-fw.text-success
        %a{:href => "javascript:void(0);"} #4831 - Paid
      %li
        %i.fa.fa-file.fa-fw.text-danger
        %a{:href => "javascript:void(0);"}
          %strong #4835 - Unpaid
  .well.well-sm.well-light
    %h5 Upcoming Meetings
    %p
      %span.label.label-success
        %i.fa.fa-check
        %strike Agenda Review @ 10 AM
    %p
      %span.label.label-primary
        %i.fa.fa-clock-o
        Client Meeting @ 2:30 PM
    %p
      %span.label.label-warning
        %i.fa.fa-clock-o
        Salary Review @ 4:00 PM
  %ul.list-inline
    %li= image_tag 'avatars/5.png', alt: 'me', width: '30px'
    %li= image_tag 'avatars/3.png', alt: 'me', width: '30px'
    %li= image_tag 'avatars/sunny.png', alt: 'me', width: '30px'
    %li
      %a{:href => "javascript:void(0);"} 1 more
:javascript
  // DO NOT REMOVE : GLOBAL FUNCTIONS!
  
  	runAllForms();
  
  	 // PAGE RELATED SCRIPTS
  
  	$(".table-wrap [rel=tooltip]").tooltip();
  
  
  
      $('#emailbody').summernote({
          height: 250,
          focus: false,
          tabsize: 2
      });
  
  
  	$(".show-next").click(function () {
  	    $this = $(this);
  	    $this.hide();
  	    $this.parent().parent().parent().parent().parent().next().removeClass("hidden");
  	})
  
  	 $("#send").click(function () {
  
  	    var $btn = $(this);
  	    $btn.button('loading');
  
  	    // wait for animation to finish and execute send script
  	    setTimeout(function () {
  	        //Insert send script here
  
  
  	        // Load inbox once send is complete
  	
  			loadURL("#{ajax_email_list_path}", $('#inbox-content > .table-wrap'))
  
  
  	    }, 1000); // how long do you want the delay to be? 
  	});

app/views/ajax/email_opened.html.haml
%h2.email-open-header
  Re: Timelogs of last client
  %span.label.txt-color-white inbox
  %a.txt-color-darken.pull-right{"data-original-title" => "Print", "data-placement" => "left", :href => "javascript:void(0);", :rel => "tooltip"}
    %i.fa.fa-print
.inbox-info-bar
  .row
    .col-sm-9
      = image_tag 'avatars/5.png', alt: 'me', class: 'away'
      %strong Sadi Orlaf
      %span.hidden-mobile
        \&lt;sadi.orlaf@smartadmin.com&gt;to
        %strong me
        on
        %i 12:10AM, 12 March 2013
    .col-sm-3.text-right
      .btn-group.text-left
        %button.btn.btn-primary.btn-sm.replythis
          %i.fa.fa-reply
          Reply
        %button.btn.btn-primary.btn-sm.dropdown-toggle{"data-toggle" => "dropdown"}
          %i.fa.fa-angle-down
        %ul.dropdown-menu.pull-right
          %li
            %a.replythis{:href => "javascript:void(0);"}
              %i.fa.fa-reply
              Reply
          %li
            %a.replythis{:href => "javascript:void(0);"}
              %i.fa.fa-mail-forward
              Forward
          %li
            %a{:href => "javascript:void(0);"}
              %i.fa.fa-print
              Print
          %li.divider
          %li
            %a{:href => "javascript:void(0);"}
              %i.fa.fa-ban
              Mark as spam!
          %li
            %a{:href => "javascript:void(0);"}
              %i.fa.fa-trash-o
              Delete forever
.inbox-message
  %p
    Hey James,
  %p
    Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
  %p
    Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit.
    %i.fa.fa-smile-o
  %br/
  %br/
  Thanks,
  %br/
  %strong Sadi Orlaf
  %br/
  %br/
  %small
    General Manager - Finance Department
    %br/
    231 Ajax Rd, Detroit MI - 48212, USA
    %br/
    %i.fa.fa-phone (313) 647 6471
  %br/
  = image_tag 'logo-blacknwhite.png', height: '20', width: 'auto', style: 'margin-top:7px; padding-right:9px; border-right:1px dotted #9B9B9B;'
.inbox-download
  2 attachment(s) —
  %a{:href => "javascript:void(0);"} Download all attachments
  %ul.inbox-download-list
    %li
      .well.well-sm
        %span
          = image_tag 'demo/sample.jpg'
        %br/
        %strong rocketlaunch.jpg
        %br/
        400 kb
        %br/
        %a{:href => "javascript:void(0);"} Download
        |
        %a{:href => "javascript:void(0);"} View
    %li
      .well.well-sm
        %span
          %i.fa.fa-file
        %br/
        %strong timelogs.xsl
        %br/
        1.3 mb
        %br/
        %a{:href => "javascript:void(0);"} Download
        |
        %a{:href => "javascript:void(0);"} Share
.email-infobox
  .well.well-sm.well-light
    %h5 Related Invoice
    %ul.list-unstyled
      %li
        %i.fa.fa-file.fa-fw.text-success
        %a{:href => "javascript:void(0);"} #4831 - Paid
      %li
        %i.fa.fa-file.fa-fw.text-danger
        %a{:href => "javascript:void(0);"}
          %strong #4835 - Unpaid
  .well.well-sm.well-light
    %h5 Upcoming Meetings
    %p
      %span.label.label-success
        %i.fa.fa-check
        %strike Agenda Review @ 10 AM
    %p
      %span.label.label-primary
        %i.fa.fa-clock-o
        Client Meeting @ 2:30 PM
    %p
      %span.label.label-warning
        %i.fa.fa-clock-o
        Salary Review @ 4:00 PM
  %ul.list-inline
    %li= image_tag 'avatars/5.png', alt: 'me', width: '30px'
    %li= image_tag 'avatars/3.png', alt: 'me', width: '30px'
    %li= image_tag 'avatars/sunny.png', alt: 'me', width: '30px'
    %li
      %a{:href => "javascript:void(0);"} 1 more
:javascript
  // DO NOT REMOVE : GLOBAL FUNCTIONS!
  //pageSetUp();
  
  // PAGE RELATED SCRIPTS
  
  $(".table-wrap [rel=tooltip]").tooltip();

  $(".replythis").click(function(){
  	loadURL("#{ajax_email_reply_path}", $('#inbox-content > .table-wrap'));
  })

app/views/ajax/email_reply.html.haml
%h2.email-open-header
  Reply to &gt; Re: Timelogs of last client
  %span.label.txt-color-white inbox
  %a.txt-color-darken.pull-right{"data-original-title" => "Print", "data-placement" => "left", :href => "javascript:void(0);", :rel => "tooltip"}
    %i.fa.fa-print
%form.form-horizontal{:action => "dummy.php", :enctype => "multipart/form-data", :method => "POST"}
  .inbox-info-bar.no-padding
    .row
      .form-group
        %label.control-label.col-md-1
          %strong To
        .col-md-11
          %select.select2{"data-select-search" => "true", :multiple => "multiple", :style => "width:100%"}
            %option{:selected => "selected", :value => "sunny.orlaf@smartadmin.com"} sunny.orlaf@smartadmin.com
            %option{:value => "rachael.hawi@smartadmin.com"} rachael.hawi@smartadmin.com
            %option{:value => "michael.safiel@smartadmin.com"} michael.safiel@smartadmin.com
            %option{:value => "alex.jones@infowars.com"} alex.jones@infowars.com
            %option{:value => "oruf.matalla@gmail.com"} oruf.matalla@gmail.com
            %option{:value => "hr@smartadmin.com"} hr@smartadmin.com
            %option{:value => "IT@smartadmin.com"} IT@smartadmin.com
          %em
            %a.show-next{"data-original-title" => "Carbon Copy", "data-placement" => "bottom", :href => "javascript:void(0);", :rel => "tooltip"} CC
  .inbox-info-bar.no-padding.hidden
    .row
      .form-group
        %label.control-label.col-md-1
          %strong CC
        .col-md-11
          %select.select2{"data-select-search" => "true", :multiple => "multiple", :style => "width:100%"}
            %option{:value => "sunny.orlaf@smartadmin.com"} sunny.orlaf@smartadmin.com
            %option{:value => "rachael.hawi@smartadmin.com"} rachael.hawi@smartadmin.com
            %option{:value => "michael.safiel@smartadmin.com"} michael.safiel@smartadmin.com
            %option{:value => "alex.jones@infowars.com"} alex.jones@infowars.com
            %option{:value => "oruf.matalla@gmail.com"} oruf.matalla@gmail.com
            %option{:value => "hr@smartadmin.com"} hr@smartadmin.com
            %option{:value => "IT@smartadmin.com"} IT@smartadmin.com
          %em
            %a.show-next{"data-original-title" => "Blind Carbon Copy", "data-placement" => "bottom", :href => "javascript:void(0);", :rel => "tooltip"} BCC
  .inbox-info-bar.no-padding.hidden
    .row
      .form-group
        %label.control-label.col-md-1
          %strong BCC
        .col-md-11
          %select.select2{"data-select-search" => "true", :multiple => "multiple", :style => "width:100%"}
            %option{:value => "sunny.orlaf@smartadmin.com"} sunny.orlaf@smartadmin.com
            %option{:value => "rachael.hawi@smartadmin.com"} rachael.hawi@smartadmin.com
            %option{:value => "michael.safiel@smartadmin.com"} michael.safiel@smartadmin.com
            %option{:value => "alex.jones@infowars.com"} alex.jones@infowars.com
            %option{:value => "oruf.matalla@gmail.com"} oruf.matalla@gmail.com
            %option{:value => "hr@smartadmin.com"} hr@smartadmin.com
            %option{:value => "IT@smartadmin.com"} IT@smartadmin.com
  .inbox-info-bar.no-padding
    .row
      .form-group
        %label.control-label.col-md-1
          %strong Subject
        .col-md-11
          %input.form-control{:placeholder => "Email Subject", :type => "text", :value => "Re: Timelogs of last client"}/
          %em
            %a.show-next{"data-original-title" => "Attachments", "data-placement" => "bottom", :href => "javascript:void(0);", :rel => "tooltip"}
              %i.fa.fa-paperclip.fa-lg
  .inbox-info-bar.no-padding.hidden
    .row
      .form-group
        %label.control-label.col-md-1
          %strong Attachments
        .col-md-11
          %input.form-control.fileinput{:multiple => "multiple", :type => "file"}/
  .inbox-message.no-padding
    #emailbody
      %br/
      = succeed "Thanks," do
        %br/
      %br/
      %strong John Doe
      %br/
      %br/
      .email-reply-text
        %p
          Sadi Orlaf
          %span.text-primary &lt;sadi.orlaf@smartadmin.com&gt;
          to me on 12:10AM, 12 March 2013
        %div
          %p
            Hey James,
          %p
            Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
          %p
            Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit.
            %i.fa.fa-smile-o
          %br/
          %br/
          Thanks,
          %br/
          %strong Sadi Orlaf
          %br/
          %br/
          %small
            General Manager - Finance Department
            %br/
            231 Ajax Rd, Detroit MI - 48212, USA
            %br/
            %i.fa.fa-phone (313) 647 6471
          %br/
          = image_tag 'logo-blacknwhite.png', height: '20', width: 'auto', style: 'margin-top:7px; padding-right:9px; border-right:1px dotted #9B9B9B;'
  .inbox-compose-footer
    %button.btn.btn-danger{:type => "button"}
      Disregard
    %button.btn.btn-info{:type => "button"}
      Draft
    %button#send.btn.btn-primary.pull-right{"data-loading-text" => "<i class='fa fa-refresh fa-spin'></i>   Sending...", :type => "button"}
      Send
      %i.fa.fa-arrow-circle-right.fa-lg
.email-infobox
  .well.well-sm.well-light
    %h5 Related Invoice
    %ul.list-unstyled
      %li
        %i.fa.fa-file.fa-fw.text-success
        %a{:href => "javascript:void(0);"} #4831 - Paid
      %li
        %i.fa.fa-file.fa-fw.text-danger
        %a{:href => "javascript:void(0);"}
          %strong #4835 - Unpaid
  .well.well-sm.well-light
    %h5 Upcoming Meetings
    %p
      %span.label.label-success
        %i.fa.fa-check
        %strike Agenda Review @ 10 AM
    %p
      %span.label.label-primary
        %i.fa.fa-clock-o
        Client Meeting @ 2:30 PM
    %p
      %span.label.label-warning
        %i.fa.fa-clock-o
        Salary Review @ 4:00 PM
  %ul.list-inline
    %li= image_tag 'avatars/5.png', alt: 'me', width: '30px'
    %li= image_tag 'avatars/3.png', alt: 'me', width: '30px'
    %li= image_tag 'avatars/sunny.png', alt: 'me', width: '30px'
    %li
      %a{:href => "javascript:void(0);"} 1 more
:javascript
  // DO NOT REMOVE : GLOBAL FUNCTIONS!
  	//pageSetUp();
  	runAllForms();
  	
  	// PAGE RELATED SCRIPTS
  	
  	$(".table-wrap [rel=tooltip]").tooltip();
  	
  
  
  		$('#emailbody').summernote({
  			height : 250,
  			focus : true,
  			tabsize : 2
  		});
  	
  	
  	$(".show-next").click(function(){
  		$this = $(this);
  		$this.hide();
  		$this.parent().parent().parent().parent().parent().next().removeClass("hidden");
  	})
  	
  	$("#send").click(function(){
  
  	    var $btn = $(this);
  	    $btn.button('loading');
  		
  		// wait for animation to finish and execute send script
  		setTimeout(function (){
  			//Insert send script here
  
  			
  			// Load inbox once send is complete
  			loadURL("#{ajax_email_list_path}", $('#inbox-content > .table-wrap'))
              
           }, 1000); // how long do you want the delay to be? 
  	});

app/views/ajax/notify_mail.html.haml
%ul.notification-body
  %li
    %span.unread
      %a.msg{:href => "javascript:void(0);"}
        = image_tag 'avatars/4.png', alt: '', class: 'air air-top-left margin-top-5', width: '40', height: '40'
        %span.from
          John Doe
          %i.icon-paperclip
        %time 2 minutes ago
        %span.subject Msed quia non numquam eius modi tempora
        %span.msg-body Hello again and thanks for being a part of the newsletter.
  %li
    %span
      %a.msg{:href => "javascript:void(0);"}
        = image_tag 'avatars/female.png', alt: '', class: 'air air-top-left margin-top-5', width: '40', height: '40'
        %span.from Sonya Birthday
        %time Thursday, September 19th
        %span.subject Incidunt ut labor
        %span.msg-body sed quia non numquam eius modi tempora incidunt ut labor
  %li
    %span
      %a.msg{:href => "javascript:void(0);"}
        = image_tag 'avatars/1.png', alt: '', class: 'air air-top-left margin-top-5', width: '40', height: '40'
        %span.from Cristina Algera
        %time Sunday, September 15th
        %span.subject Best-Selling Teethers
        %span.msg-body ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?
  %li
    %span
      %a.msg{:href => "javascript:void(0);"}
        = image_tag 'avatars/male.png', alt: '', class: 'air air-top-left margin-top-5', width: '40', height: '40'
        %span.from Lam Tampora
        %time Saturday, September 14th
        %span.subject Deadline due date
        %span.msg-body imus qui blanditiis praesentium voluptatum deleniti atque corrup
  %li
    %span.unread
      %a.msg{:href => "javascript:void(0);"}
        = image_tag 'avatars/sunny.png', alt: '', class: 'air air-top-left margin-top-5', width: '40', height: '40'
        %span.from
          Project approved!
          %i.icon-paperclip
        %time September 14th
        %span.subject Et harum quidem rerum facilis est et expedita distinctio
        %span.msg-body ...
  %li
    %span
      %a.msg{:href => "javascript:void(0);"}
        = image_tag 'avatars/male.png', alt: '', class: 'air air-top-left margin-top-5', width: '40', height: '40'
        %span.from JEFF, me
        %time Friday, September 13th
        %span.subject Bugs fixed!
        %span.msg-body Nam libero tempore, cum soluta nobis est eligendi optio cumque