config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'miscellaneous#blank_page'

  # AJAX
  get 'ajax/email_compose', to: 'ajax#email_compose', as: :ajax_email_compose
  get 'ajax/email_list', to: 'ajax#email_list', as: :ajax_email_list
  get 'ajax/email_opened', to: 'ajax#email_opened', as: :ajax_email_opened
  get 'ajax/email_reply', to: 'ajax#email_reply', as: :ajax_email_reply
  get 'ajax/demo_widget', to: 'ajax#demo_widget', as: :ajax_demo_widget
  get 'ajax/data_list.json', to: 'ajax#data_list', as: :ajax_data_list
  get 'ajax/notify_mail', to: 'ajax#notify_mail', as: :ajax_notify_mail
  get 'ajax/notify_notifications',
      to: 'ajax#notify_notifications',
      as: :ajax_notify_notifications
  get 'ajax/notify_tasks', to: 'ajax#notify_tasks', as: :ajax_notify_tasks

  # Misc methods
  get '/home/set_locale', to: 'home#set_locale', as: :home_set_locale

  # CK editor
  mount Ckeditor::Engine => '/ckeditor'
  
  # WX base
  get 'wx/messages', to: 'wx_base#verify_token'
  post 'wx/messages', to: 'wx_base#messages'
  
  # WX page
  get 'messages', to: 'wx_page#messages'
  get 'followers', to: 'wx_page#followers'
  
  # SN Generator
  get 'sn', to: 'series_number#list'
  get 'sn/new', to: 'series_number#new'
  post 'sn/new', to: 'series_number#new'
  get 'sn/dl/:key', to: 'series_number#download', as: :sn_dl

end

app/controllers/series_number_controller.rb
class SeriesNumberController < ApplicationController

  def list
    @batch = SeriesBatch.paginate(page: params[:page]).order('id DESC')
  end

  def new
    cfg = {
      :count => params[:count] || 50,
      :length => params[:length] || 12,
      :number => params[:number] == "1",
      :alphabet => params[:alphabet] == "1",
      :friendly => params[:friendly] == "1",
      :case_sensitive => params[:case_sensitive] == "1",
      :prefix => params[:prefix] || "",
      :surfix => "",
    }
    if request.post?
      redis = Redis.new
      redis_key = "set_" + get_random_string
      puts redis_key
      
      _pool = "";
      if cfg[:number]
        _pool += (0..9).to_a.join
      end
      if cfg[:alphabet]
        if cfg[:friendly]
          _pool += "CEFGHKMNPQRTWXY"
        else
          _pool += ("A".."Z").to_a.join
        end
      end
      if cfg[:case_sensitive]
        if cfg[:friendly]
          _pool += "adefghijr"
        else
          _pool += ("a".."z").to_a.join
        end
      end
      # 准备字库

      rand_len = cfg[:length].to_i - cfg[:prefix].size - cfg[:surfix].size
      pool_len = _pool.size
      possibility = pool_len ** rand_len
      gaps = possibility / cfg[:count].to_i
      puts possibility, gaps, pool_len

      # seed = 0
      cfg[:count].to_i.times do |i|
        # seed += SecureRandom.random_number(gaps) + 1

        arr = nil
        count = 0
        while !arr || (!count && possibility >= cfg[:count].to_i)
          arr = gen_code possibility, pool_len, rand_len
          # (rand_len - 1).times { arr.push rand(pool_len) }
          count = redis.sadd redis_key, cfg[:prefix] + (arr.map { |item| _pool[item] }).join + cfg[:surfix]
        end
        # puts arr.to_json
      end
      redis.expire redis_key, 300
    elsif request.get?
      cfg[:number] ||= true
      cfg[:friendly] ||= true
    end

    render :locals => {
      cfg: cfg,
      list: (defined? redis) && !redis.nil? && redis.smembers(redis_key).sort || nil,
      gaps: gaps || 0,
      key: redis_key
    }
  end
  
  def download
    key = params[:key]
    if !key.nil? && !key.empty?
      redis = Redis.new
      list = redis.smembers key
      if list.size > 0
        respond_to do |format|
          format.xlsx {
            require 'axlsx'

            Axlsx::Package.new do |p|
              p.workbook.add_worksheet(:name => "List") do |sheet|
                sheet.add_row ["Code"]
                list.sort.each { |label| sheet.add_row [label], :types => [:string] }
              end
              
              send_data p.to_stream.read, filename: "code_#{DateTime.now.to_i.to_s}.xlsx"
            end
          }
          format.csv { send_data list.sort.to_csv, filename: "code_#{DateTime.now.to_i.to_s}.csv" }
        end
      else
        render plain: "Expired", status: 400
      end
    else
      render plain: "Missing params: key", status: 400
    end
  end
  
  private
  
  def get_random_string(length = 8, map = nil)
    map = ("a".."z").to_a + ("A".."Z").to_a + (0..9).to_a if map.nil?
    key = ""
    length.times { key += map[rand(map.size)].to_s }
    key
  end
  
  def gen_code(max, count, len)
    num = SecureRandom.random_number(max)
    arr = [num % count]
    while (num -= arr[0]) > 0
      num /= count
      arr.unshift num % count
    end
    if arr.size < len
      zero = Array.new(len - arr.size)
      zero.fill(0) + arr;
    elsif arr.size > len
      return nil
    else
      arr
    end
  end
  
end

app/helpers/series_number_helper.rb
module SeriesNumberHelper
end

app/views/series_number/list.html.haml
- content_for :ribbon do
  / RIBBON
  #ribbon
    / breadcrumb
    %ol.breadcrumb
      %li Home
      %li Series Number Generator
    / end breadcrumb

  / END RIBBON

/ #MAIN CONTENT
#content
  .row
    .col-xs-12.col-sm-7.col-md-7.col-lg-4
      %h1.page-title.txt-color-blueDark
        / PAGE HEADER
        %i.fa-fw.fa.fa-comments
        Series Number
        %span
          \&gt;
          Batch
  .row
    .col-sm-12
      - unless @batch.empty?
        .table-responsive
          %table.table.table-striped.table-hover.dataTable.no-footer
            %thead
              %tr
                %th ID
                %th Summary
                %th Time
            %tbody
              - @batch.each do |batch|
                %tr
                  %td= batch.id
                  %td= batch.summary
                  %td= batch.created_at.strftime("%Y-%m-%d %H:%M:%S")
      - else
        .well
          %p.alert.alert-info
            %i.fa.fa-info
            No batch found!
      .col-xs-12.col-sm-6
        = will_paginate @batch

/ END #MAIN CONTENT

app/views/series_number/new.html.haml
- content_for :ribbon do
  / RIBBON
  #ribbon
    / breadcrumb
    %ol.breadcrumb
      %li Home
      %li Series Code Generator
    / end breadcrumb

  / END RIBBON

/ #MAIN CONTENT
#content
  .row
    .col-xs-12.col-sm-7.col-md-7.col-lg-4
      %h1.page-title.txt-color-blueDark
        / PAGE HEADER
        %i.fa.fa-fw.fa-comments
        Series Code
        %span
          \&gt;
          Generate

  %section#widget-grid
    .row
      %article.col-xs-12.col-sm-12.com-md-4.col-lg-4
        .jarviswidget#wid-id-0(data-widget-editbutton="false")
          %header
            %span.widget-icon
              %i.fa.fa-edit
            %h2 Form
          %div
            .jarviswidget-editbox
            .widget-body.no-padding
              = form_tag sn_new_path, class: 'smart-form' do
                %header Basic
                %fieldset
                  %section
                    = label_tag :count, nil, class: 'label'
                    %label.input
                      = number_field_tag :count, cfg[:count], min: 10, step: 10, required: true

                %header Format
                %fieldset
                  %section
                    = label_tag :length, nil, class: 'label'
                    %label.input
                      = number_field_tag :length, cfg[:length], in: 4..32, required: true
                    .note
                      %i.fa-fw.fa.fa-info-circle
                      Prefix length included
                %fieldset
                  %section
                    %label.label Include
                    %label.toggle
                      = check_box_tag :number, "1", cfg[:number]
                      %i(data-swchon-text="ON" data-swchoff-text="OFF")
                      Number
                    %label.toggle
                      = check_box_tag :alphabet, "1", cfg[:alphabet]
                      %i(data-swchon-text="ON" data-swchoff-text="OFF")
                      Alphabet
                    %label.toggle
                      = check_box_tag :friendly, "1", cfg[:friendly]
                      %i(data-swchon-text="ON" data-swchoff-text="OFF")
                      Friendly letters only
                  %section
                    %label.label Misc
                    %label.toggle
                      = check_box_tag :case_sensitive, "1", cfg[:case_sensitive]
                      %i(data-swchon-text="ON" data-swchoff-text="OFF")
                      Case sensitive

                %header Output
                %fieldset
                  %section
                    = label_tag :prefix, nil, class: 'label'
                    %label.input
                      = text_field_tag :prefix, cfg[:prefix]

                %footer
                  = button_tag "Submit", class: "btn btn-primary"
                  = button_tag "Reset", class: "btn btn-default", type: "reset"

      %article.col-xs-12.col-sm-12.com-md-8.col-lg-8
        - if list.nil?
          .alert.alert-info.no-margin
            %p.text-default
              %i.fa-fw.fa.fa-info
              To generate new codes, setting up options if needed then press <b>"Submit"</b>.
        - else
          .jarviswidget#wid-id-1(data-widget-editbutton="false")
            %header
              .jarviswidget-ctrls
                %a.button-icon.jarviswidget-toggle-btn(data-toggle="modal" data-target="#downloadModal" rel="tooltip" data-original-title="Save")
                  %i.fa.fa-download
              %span.widget-icon
                %i.fa.fa-database
              %h2
                Result (key:
                = key
                )
            %div
              .jarviswidget-editbox
              .widget-body.no-padding
                .row.codes
                  .col-md-12
                    - if gaps < 500
                      .alert.alert-warning
                        %i.fa-fw.fa.fa-warning
                        Lack of variety codes are easy to guess, please do
                        %b NOT
                        use in production environment.
                    - if list.size < params[:count].to_i
                      .alert.alert-warning
                        %i.fa-fw.fa.fa-warning
                        %b Length
                        is too small to generate enough unique codes.
                    .alert.alert-info
                      %i.fa-fw.fa.fa-info
                      = number_with_delimiter list.size
                      records.
                  - list.each do |item|
                    .col-md-3.code= item

  - unless key.nil?
    #downloadModal.modal.fade(tabindex="-1")
      .modal-dialog
        .modal-content
          .modal-header
            %button.close(type="button" data-dismiss="modal")
              &times;
            %h4.modal-title Download
          .modal-body
            .row
              .col-md-12
                %p Choose a format to download:
                %ul
                  %li
                    = link_to sn_dl_path(key, 'csv'), class: 'button-icon jarviswidget-toggle-btn', target: '_blank' do
                      %i.fa.fa-file-text-o
                      CSV
                  %li
                    = link_to sn_dl_path(key, 'xlsx'), class: 'button-icon jarviswidget-toggle-btn', target: '_blank' do
                      %i.fa.fa-file-excel-o
                      Excel 2007
          .modal-footer
            %button.btn.btn-default(type="button" data-dismiss="modal") Close
/ END #MAIN CONTENT