config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'miscellaneous#blank_page'

  # AJAX
  get 'ajax/email_compose', to: 'ajax#email_compose', as: :ajax_email_compose
  get 'ajax/email_list', to: 'ajax#email_list', as: :ajax_email_list
  get 'ajax/email_opened', to: 'ajax#email_opened', as: :ajax_email_opened
  get 'ajax/email_reply', to: 'ajax#email_reply', as: :ajax_email_reply
  get 'ajax/demo_widget', to: 'ajax#demo_widget', as: :ajax_demo_widget
  get 'ajax/data_list.json', to: 'ajax#data_list', as: :ajax_data_list
  get 'ajax/notify_mail', to: 'ajax#notify_mail', as: :ajax_notify_mail
  get 'ajax/notify_notifications',
      to: 'ajax#notify_notifications',
      as: :ajax_notify_notifications
  get 'ajax/notify_tasks', to: 'ajax#notify_tasks', as: :ajax_notify_tasks

  # Misc methods
  get '/home/set_locale', to: 'home#set_locale', as: :home_set_locale

  # CK editor
  mount Ckeditor::Engine => '/ckeditor'
  
  # WX base
  get 'wx/messages', to: 'wx_base#verify_token'
  post 'wx/messages', to: 'wx_base#messages'
  
  # WX page
  get 'messages', to: 'wx_page#messages'
  get 'followers', to: 'wx_page#followers'
  
  # SN Generator
  get 'sn', to: 'series_number#list'
  get 'sn/new', to: 'series_number#new'
  post 'sn/new', to: 'series_number#new'
  get 'sn/dl/:key', to: 'series_number#download', as: :sn_dl

end

app/views/layouts/_footer.html.haml
.page-footer
  .row
    .col-xs-12.col-sm-6
      %span.txt-color-white
        SmartAdmin 1.8.x
        %span.hidden-xs - Web Application Framework
        © 2014-2017

app/views/layouts/_header.html.haml
%header#header
  #logo-group
    / PLACE YOUR LOGO HERE
    %span#logo
      = image_tag 'logo.png', alt: 'SmartAdmin'
    / END LOGO PLACEHOLDER
    - if current_user && !@simulate_no_user
      /
        Note: The activity badge color changes when clicked and resets the number to 0
        Suggestion: You may want to set a flag when this happens to tick off all checked messages / notifications
      %span#activity.activity-dropdown
        %i.fa.fa-user
        %b.badge 21
      / AJAX-DROPDOWN : control this dropdown height, look and feel from the LESS variable file
      .ajax-dropdown
        / the ID links are fetched via AJAX to the ajax container "ajax-notifications"
        .btn-group.btn-group-justified{"data-toggle" => "buttons"}
          %label.btn.btn-default
            %input{:id => ajax_notify_mail_path, :name => "activity", :type => "radio"}/
            = _('Msgs')
            (14)
          %label.btn.btn-default
            %input{:id => ajax_notify_notifications_path, :name => "activity", :type => "radio"}/
            = _('notify')
            (3)
          %label.btn.btn-default
            %input{:id => ajax_notify_tasks_path, :name => "activity", :type => "radio"}/
            = _('Tasks')
            (4)
        / notification content
        .ajax-notifications.custom-scroll
          .alert.alert-transparent
            %h4 Click a button to show messages here
            This blank page message helps protect your privacy, or you can show the first message here automatically.
          %i.fa.fa-lock.fa-4x.fa-border
        / end notification content
        / footer: refresh area
        %span
          Last updated on: 12/12/2013 9:43AM
          %button.btn.btn-xs.btn-default.pull-right{"data-loading-text" => "<i class='fa fa-refresh fa-spin'></i> Loading...", :type => "button"}
            %i.fa.fa-refresh
        / end footer
      / END AJAX-DROPDOWN
  = yield :top_right
  - if current_user && !@simulate_no_user
    / projects dropdown
    .project-context.hidden-xs
      %span.label Projects:
      %span.project-selector.dropdown-toggle{"data-toggle" => "dropdown"}
        = _('Recent projects')
        %i.fa.fa-angle-down
      / Suggestion: populate this list with fetch and push technique
      %ul.dropdown-menu
        %li
          %a{:href => "javascript:void(0);"} Online e-merchant management system - attaching integration with the iOS
        %li
          %a{:href => "javascript:void(0);"} Notes on pipeline upgradee
        %li
          %a{:href => "javascript:void(0);"} Assesment Report for merchant account
        %li.divider
        %li
          %a{:href => "javascript:void(0);"}
            %i.fa.fa-power-off
            Clear
      / end dropdown-menu
    / end projects dropdown
    / pulled right: nav area
    .pull-right
      / collapse menu button
      #hide-menu.btn-header.pull-right
        %span
          %a{"data-action" => "toggleMenu", :href => "javascript:void(0);", :title => "Collapse Menu"}
            %i.fa.fa-reorder
      / end collapse menu
      / #MOBILE
      / Top menu profile link : this shows only when top menu is active
      %ul#mobile-profile-img.header-dropdown-list.hidden-xs.padding-5
        %li
          %a.dropdown-toggle.no-margin.userdropdown{"data-toggle" => "dropdown", :href => "#"}
            = image_tag 'avatars/sunny.png', alt: 'John Doe', class: 'online'
          %ul.dropdown-menu.pull-right
            %li
              %a.padding-10.padding-top-0.padding-bottom-0{:href => "javascript:void(0);"}
                %i.fa.fa-cog
                Setting
            %li.divider
            %li
              %a.padding-10.padding-top-0.padding-bottom-0{:href => "profile.html"}
                %i.fa.fa-user
                = succeed "rofile" do
                  %u P
            %li.divider
            %li
              %a.padding-10.padding-top-0.padding-bottom-0{"data-action" => "toggleShortcut", :href => "javascript:void(0);"}
                %i.fa.fa-arrow-down
                = succeed "hortcut" do
                  %u S
            %li.divider
            %li
              %a.padding-10.padding-top-0.padding-bottom-0{"data-action" => "launchFullscreen", :href => "javascript:void(0);"}
                %i.fa.fa-arrows-alt
                Full
                = succeed "creen" do
                  %u S
            %li.divider
            %li
              %a.padding-10.padding-top-5.padding-bottom-5{"data-action" => "userLogout", :href => "login.html"}
                %i.fa.fa-sign-out.fa-lg
                %strong
                  %u> L
                  ogout
      / logout button
      #logout.btn-header.transparent.pull-right
        %span
          = link_to(destroy_user_session_path, title: 'Sign Out', data: {action: 'userLogout', 'logout-msg' => 'You can improve your security further after logging out by closing this opened browser'}) do
            %i.fa.fa-sign-out
      / end logout button
      / search mobile button (this is hidden till mobile view port)
      #search-mobile.btn-header.transparent.pull-right
        %span
          %a{:href => "javascript:void(0)", :title => "Search"}
            %i.fa.fa-search
      / end search mobile button
      / input: search field
      %form.header-search.pull-right{:action => root_path}
        %input#search-fld{"data-autocomplete" => "[\n            \"ActionScript\",\n            \"AppleScript\",\n            \"Asp\",\n            \"BASIC\",\n            \"C\",\n            \"C++\",\n            \"Clojure\",\n            \"COBOL\",\n            \"ColdFusion\",\n            \"Erlang\",\n            \"Fortran\",\n            \"Groovy\",\n            \"Haskell\",\n            \"Java\",\n            \"JavaScript\",\n            \"Lisp\",\n            \"Perl\",\n            \"PHP\",\n            \"Python\",\n            \"Ruby\",\n            \"Scala\",\n            \"Scheme\"]", :name => "param", :placeholder => "#{_('Find reports and more')}", :type => "text"}/
        %button{:type => "submit"}
          %i.fa.fa-search
        %a#cancel-search-js{:href => "javascript:void(0);", :title => "Cancel Search"}
          %i.fa.fa-times
      / end input: search field
      / fullscreen button
      #fullscreen.btn-header.transparent.pull-right
        %span
          %a{"data-action" => "launchFullscreen", :href => "javascript:void(0);", :title => "Full Screen"}
            %i.fa.fa-arrows-alt
      / end fullscreen button
      / multiple lang dropdown : find all flags in the flags page
      = render 'layouts/locale_select'
      / end multiple lang
    / end pulled right: nav area

app/views/layouts/_left_panel.html.haml
%aside#left-panel
  / User info
  .login-info
    %span
      / User image size is adjusted inside CSS, it should stay as it
      %a#show-shortcut{"data-action" => "toggleShortcut", :href => "javascript:void(0);"}
        = image_tag 'avatars/sunny.png', alt: 'me', class: 'online'
        %span= current_user.name || 'User'
        %i.fa.fa-angle-down
  / end user info
  / NAVIGATION : This navigation is also responsive
  %nav
    /
      NOTE: Notice the gaps after each icon usage <i></i>..
      Please note that these links work a bit different than
      traditional href="" links. See documentation for details.
    %ul
      = left_menu
  %span.minifyme{"data-action" => "minifyMenu"}
    %i.fa.fa-arrow-circle-left.hit

app/views/layouts/_locale_select.html.haml
- @selected_locale = selected_locale
%ul.header-dropdown-list.hidden-xs
  %li
    = link_to '#', class: 'dropdown-toggle', data: {toggle: 'dropdown'} do
      = image_tag "blank.gif", class: "flag flag-#{@selected_locale[:flag]}", alt: @selected_locale[:alt_name]
      %span
        = @selected_locale[:name]
      %i.fa.fa-angle-down
    %ul.dropdown-menu.pull-right
      - locale_list.each do |locale|
        %li{:class => "#{'active' if locale[:locale] == @selected_locale[:locale]}"}
          = link_to home_set_locale_path(locale: locale[:locale]) do
            = image_tag "blank.gif", class: "flag flag-#{locale[:flag]}", alt: locale[:alt_name]
            = locale[:name]

app/views/layouts/_scripts.html.haml
:javascript
  $(document).ready(function() {
    pageSetUp();
  })

app/views/layouts/_tiles.html.haml
#shortcut
  %ul
    %li
      = link_to root_path, class: 'jarvismetro-tile big-cubes bg-color-blue' do
        %span.iconbox
          %i.fa.fa-envelope.fa-4x
          %span
            Mail
            %span.label.pull-right.bg-color-darken 14
    %li
      = link_to root_path, class: 'jarvismetro-tile big-cubes bg-color-orangeDark' do
        %span.iconbox
          %i.fa.fa-calendar.fa-4x
          %span Calendar
    %li
      = link_to root_path, class: 'jarvismetro-tile big-cubes bg-color-purple' do
        %span.iconbox
          %i.fa.fa-map-marker.fa-4x
          %span Maps
    %li
      = link_to root_path, class: 'jarvismetro-tile big-cubes bg-color-blueDark' do
        %span.iconbox
          %i.fa.fa-book.fa-4x
          %span
            Invoice
            %span.label.pull-right.bg-color-darken 99
    %li
      = link_to root_path, class: 'jarvismetro-tile big-cubes bg-color-greenLight' do
        %span.iconbox
          %i.fa.fa-picture-o.fa-4x
          %span Gallery
    %li
      = link_to root_path, class: 'jarvismetro-tile big-cubes selected bg-color-pinkDark' do
        %span.iconbox
          %i.fa.fa-user.fa-4x
          %span My Profile

app/views/layouts/application.html.haml
!!!
%html{:id => "#{yield :html_id}", :lang => "en-us"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %title SmartAdmin - Ruby on Rails
    = csrf_meta_tags
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", :name => "viewport"}/
    = stylesheet_link_tag 'application', media: 'screen'
    / FAVICONS
    = favicon_link_tag 'favicon/favicon.ico'
    = favicon_link_tag 'favicon/favicon.ico', rel: 'icon'
    /
      Specifying a Webpage Icon for Web Clip
      Ref: https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html
    = favicon_link_tag 'splash/sptouch-icon-iphone.png', type: 'image/png', rel: 'apple-touch-icon'
    = favicon_link_tag 'splash/touch-icon-ipad.png', type: 'image/png', sizes: '76x76', rel: 'apple-touch-icon'
    = favicon_link_tag 'splash/touch-icon-iphone-retina.png', type: 'image/png', sizes: '120x120', rel: 'apple-touch-icon'
    = favicon_link_tag 'splash/touch-icon-ipad-retina.png', type: 'image/png', sizes: '152x152', rel: 'apple-touch-icon'
    / iOS web-app metas : hides Safari UI Components and Changes Status Bar Appearance
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
    %meta{:content => "black", :name => "apple-mobile-web-app-status-bar-style"}/
    / Startup image for web apps
    = favicon_link_tag 'splash/ipad-landscape.png', type: 'image/png', rel: 'apple-touch-startup-image', media: 'screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)'
    = favicon_link_tag 'splash/ipad-portrait.png', type: 'image/png', rel: 'apple-touch-startup-image', media: 'screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)'
    = favicon_link_tag 'splash/iphone.png', type: 'image/png', rel: 'apple-touch-startup-image', media: 'screen and (max-device-width: 320px)'
    = yield :head
  /
    TABLE OF CONTENTS.
    
    Use search to find needed section.
    
    \===================================================================
    
    |  01. #CSS Links                |  all CSS links and file paths  |
    |  02. #FAVICONS                 |  Favicon links and file paths  |
    |  03. #GOOGLE FONT              |  Google font link              |
    |  04. #APP SCREEN / ICONS       |  app icons, screen backdrops   |
    |  05. #BODY                     |  body tag                      |
    |  06. #HEADER                   |  header tag                    |
    |  07. #PROJECTS                 |  project lists                 |
    |  08. #TOGGLE LAYOUT BUTTONS    |  layout buttons and actions    |
    |  09. #MOBILE                   |  mobile view dropdown          |
    |  10. #SEARCH                   |  search field                  |
    |  11. #NAVIGATION               |  left panel & navigation       |
    |  12. #RIGHT PANEL              |  right panel userlist          |
    |  13. #MAIN PANEL               |  main panel                    |
    |  14. #MAIN CONTENT             |  content holder                |
    |  15. #PAGE FOOTER              |  page footer                   |
    |  16. #SHORTCUT AREA            |  dropdown shortcuts area       |
    |  17. #PLUGINS                  |  all scripts and plugins       |
    
    \===================================================================
  / #BODY
  /
    Possible Classes
    
    * 'smart-style-{SKIN#}'
    * 'smart-rtl'         - Switch theme mode to RTL
    * 'menu-on-top'       - Switch to top navigation (no DOM change required)
    * 'no-menu'			      - Hides the menu completely
    * 'hidden-menu'       - Hides the main menu but still accessable by hovering over left edge
    * 'fixed-header'      - Fixes the header
    * 'fixed-navigation'  - Fixes the main menu
    * 'fixed-ribbon'      - Fixes breadcrumb
    * 'fixed-page-footer' - Fixes footer
    * 'container'         - boxed layout mode (non-responsive: will not work with fixed-navigation & fixed-ribbon)
  %body{:class => "#{yield :body_class}"}
    / HEADER
    = render partial: 'layouts/header' unless @lock_screen
    / END HEADER
    / Left panel : Navigation area
    / Note: This width of the aside area can be adjusted through LESS variables
    = render partial: 'layouts/left_panel' if current_user && !@simulate_no_user
    / END NAVIGATION
    / MAIN PANEL
    #main{:role => "main"}
      = yield :ribbon
      - if notice
        .alert.alert-success.fade.in
          %button.close{"data-dismiss" => "alert"}
            ×
          %i.fa-fw.fa.fa-check
          = notice
      - if alert
        .alert.alert-warning.fade.in
          %button.close{"data-dismiss" => "alert"}
            ×
          %i.fa-fw.fa.fa-warning
          = alert
      = yield
    / END MAIN PANEL
    / PAGE FOOTER
    = render partial: 'layouts/footer' if current_user && !@simulate_no_user
    / END PAGE FOOTER
    /
      SHORTCUT AREA : With large tiles (activated via clicking user name tag)
      Note: These tiles are completely responsive,
      you can add as many as you like
    = render partial: 'layouts/tiles' if current_user && !@simulate_no_user
    / END SHORTCUT AREA
    / ==================================================
    / PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)
    = javascript_include_tag 'plugin/pace/pace', 'data-pace-options' => '{ "restartOnRequestAfter": true }'
    = javascript_include_tag 'application'
    /[if IE 8]
      <h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>
    = yield(:scripts).present? ? yield(:scripts) : render(partial: 'layouts/scripts')
    / Your GOOGLE ANALYTICS CODE Below
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-XXXXXXXX-X']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script');
        ga.type = 'text/javascript';
        ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(ga, s);
      })();